info:
  contact: {}
paths:
  /dummy/{id}:
    get:
      parameters:
      - description: Dummy id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Return simple dummy object
      tags:
      - dummy
swagger: "2.0"
